Connected to Python 3.13.0

In [154]:
import pandas as pd

In [155]:
car=pd.read_csv(r"cars_datasets.csv")

In [156]:
car.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Honda,F-150,SUV,Asia,FWD,26536,63726,2.7,8.0,225,15,25,5756,95.2,223.9
1,BMW,F-150,Truck,USA,RWD,43541,19704,1.9,4.0,494,21,24,3728,111.3,199.6
2,Chevrolet,A4,Truck,Asia,FWD,28547,74576,5.4,8.0,404,21,36,5319,115.0,172.8
3,BMW,Corolla,Truck,USA,4WD,66027,21848,2.1,6.0,468,30,39,5785,105.6,169.8
4,BMW,Civic,SUV,USA,FWD,49531,35592,4.5,NaN,393,17,31,2755,106.1,200.4

In [157]:
car.shape

(421, 15)

 1. For Data Cleaning - Find all Null Values in the dataset. If there is any null value in any column, then fill it with the mean of that column.

In [158]:
car.isnull()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
417,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
418,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
419,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
420,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [159]:
car.isnull().sum()

Make            0
Model           0
Type            0
Origin          0
DriveTrain      0
MSRP            0
Invoice         0
EngineSize      0
Cylinders      20
Horsepower      0
MPG_City        0
MPG_Highway     0
Weight          0
Wheelbase       0
Length          0
dtype: int64

In [160]:
car['Cylinders'].fillna(car['Cylinders'].mean(), inplace=True)

C:\Users\napal\AppData\Local\Temp\ipykernel_24284\4255458296.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car['Cylinders'].fillna(car['Cylinders'].mean(), inplace=True)

In [161]:
car.isnull().sum()

Make           0
Model          0
Type           0
Origin         0
DriveTrain     0
MSRP           0
Invoice        0
EngineSize     0
Cylinders      0
Horsepower     0
MPG_City       0
MPG_Highway    0
Weight         0
Wheelbase      0
Length         0
dtype: int64

2.Based on Value Counts - Check what are the different types of Make are there in our dataset. And, what is the count (occurrence) of each Make in the data ?

In [162]:
car.head(2)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Honda,F-150,SUV,Asia,FWD,26536,63726,2.7,8.0,225,15,25,5756,95.2,223.9
1,BMW,F-150,Truck,USA,RWD,43541,19704,1.9,4.0,494,21,24,3728,111.3,199.6

In [163]:
car['Make'].value_counts()

Make
Honda        81
Toyota       80
Audi         71
Chevrolet    71
Ford         61
BMW          57
Name: count, dtype: int64

3. Filtering  - Show all the records where Origin is Asia or Europe.

In [164]:
car[car['Origin'].isin(['Asia','Europe'])]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Honda,F-150,SUV,Asia,FWD,26536,63726,2.7,8.0,225,15,25,5756,95.2,223.9
2,Chevrolet,A4,Truck,Asia,FWD,28547,74576,5.4,8.0,404,21,36,5319,115.0,172.8
6,Chevrolet,A4,Coupe,Asia,4WD,53565,20924,5.9,8.0,424,31,30,3374,126.2,214.7
8,Chevrolet,Cruze,SUV,Europe,RWD,71251,66980,5.8,8.0,275,13,29,4635,109.2,174.3
9,BMW,Civic,SUV,Asia,AWD,79213,33614,1.5,4.0,215,30,39,5535,95.5,161.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,Ford,A4,Sedan,Asia,AWD,41984,19772,4.5,4.0,492,26,25,4175,126.4,204.0
414,Audi,A4,Truck,Asia,4WD,59633,62244,1.7,4.0,315,25,19,2798,122.8,225.1
415,Chevrolet,Cruze,SUV,Asia,RWD,23125,65681,3.3,8.0,363,32,29,3456,100.5,207.3
416,Toyota,Corolla,Sedan,Asia,AWD,51059,62519,5.2,8.0,362,19,42,5346,96.8,181.5
419,BMW,3 Series,Sedan,Europe,RWD,32087,31347,5.5,6.0,102,18,36,5120,124.2,215.3

4. Removing unwanted records  - Remove all the records (rows) where Weight is above 4000.

In [165]:
car.head(2)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Honda,F-150,SUV,Asia,FWD,26536,63726,2.7,8.0,225,15,25,5756,95.2,223.9
1,BMW,F-150,Truck,USA,RWD,43541,19704,1.9,4.0,494,21,24,3728,111.3,199.6

In [166]:
car[~(car['Weight']>4000)]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
1,BMW,F-150,Truck,USA,RWD,43541,19704,1.9,4.000000,494,21,24,3728,111.3,199.6
4,BMW,Civic,SUV,USA,FWD,49531,35592,4.5,5.930175,393,17,31,2755,106.1,200.4
5,Ford,F-150,Coupe,USA,RWD,23712,59743,6.2,4.000000,163,31,18,2634,128.6,213.3
6,Chevrolet,A4,Coupe,Asia,4WD,53565,20924,5.9,8.000000,424,31,30,3374,126.2,214.7
7,Chevrolet,A4,SUV,USA,RWD,24208,41208,2.9,4.000000,491,10,34,3321,124.7,179.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407,Audi,F-150,Sedan,USA,4WD,28598,62563,2.3,4.000000,199,33,20,3705,115.1,211.3
408,Audi,Civic,SUV,Europe,4WD,62055,25138,4.6,8.000000,208,31,40,3392,99.8,224.7
414,Audi,A4,Truck,Asia,4WD,59633,62244,1.7,4.000000,315,25,19,2798,122.8,225.1
415,Chevrolet,Cruze,SUV,Asia,RWD,23125,65681,3.3,8.000000,363,32,29,3456,100.5,207.3
417,Ford,Corolla,SUV,USA,FWD,19033,49732,5.6,4.000000,391,19,32,3614,114.5,185.9

5. Applying function on a column  - Increase all the values of 'MPG_City' column by 3.

In [167]:
car.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Honda,F-150,SUV,Asia,FWD,26536,63726,2.7,8.000000,225,15,25,5756,95.2,223.9
1,BMW,F-150,Truck,USA,RWD,43541,19704,1.9,4.000000,494,21,24,3728,111.3,199.6
2,Chevrolet,A4,Truck,Asia,FWD,28547,74576,5.4,8.000000,404,21,36,5319,115.0,172.8
3,BMW,Corolla,Truck,USA,4WD,66027,21848,2.1,6.000000,468,30,39,5785,105.6,169.8
4,BMW,Civic,SUV,USA,FWD,49531,35592,4.5,5.930175,393,17,31,2755,106.1,200.4

In [168]:
car['MPG_City']=car['MPG_City'].apply(lambda x:x+3)

In [169]:
car

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Honda,F-150,SUV,Asia,FWD,26536,63726,2.7,8.000000,225,18,25,5756,95.2,223.9
1,BMW,F-150,Truck,USA,RWD,43541,19704,1.9,4.000000,494,24,24,3728,111.3,199.6
2,Chevrolet,A4,Truck,Asia,FWD,28547,74576,5.4,8.000000,404,24,36,5319,115.0,172.8
3,BMW,Corolla,Truck,USA,4WD,66027,21848,2.1,6.000000,468,33,39,5785,105.6,169.8
4,BMW,Civic,SUV,USA,FWD,49531,35592,4.5,5.930175,393,20,31,2755,106.1,200.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,Toyota,Corolla,Sedan,Asia,AWD,51059,62519,5.2,8.000000,362,22,42,5346,96.8,181.5
417,Ford,Corolla,SUV,USA,FWD,19033,49732,5.6,4.000000,391,22,32,3614,114.5,185.9
418,Audi,3 Series,SUV,USA,RWD,52873,53905,3.1,5.930175,373,14,16,5027,100.5,198.5
419,BMW,3 Series,Sedan,Europe,RWD,32087,31347,5.5,6.000000,102,21,36,5120,124.2,215.3
420,Audi,A4,Truck,USA,AWD,55901,30920,6.3,8.000000,127,29,25,5005,107.5,182.3